"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "../../lib/supabase";

export default function AdminPage() {
  const [allowed,setAllowed]=useState(false); const [loading,setLoading]=useState(true); const [reports,setReports]=useState<any[]>([]); const [announcement,setAnnouncement]=useState({title:"",content:""}); const [message,setMessage]=useState("");
  useEffect(()=>{check();},[]);
  async function check(){ if(!supabase){setLoading(false);return;} const {data:s}=await supabase.auth.getSession(); if(!s.session){setLoading(false);return;} const {data:a}=await supabase.from("admin_users").select("user_id").eq("user_id",s.session.user.id).maybeSingle(); setAllowed(Boolean(a)); if(a){const {data:r}=await supabase.from("reports").select("id,reason,status,created_at,post_id,comment_id").order("created_at",{ascending:false}).limit(100);setReports(r??[]);} setLoading(false); }
  async function publish(){if(!supabase||!announcement.title.trim()||!announcement.content.trim())return;const {error}=await supabase.from("announcements").insert({title:announcement.title.trim(),content:announcement.content.trim()});setMessage(error?"공지 등록에 실패했습니다.":"공지를 등록했습니다.");if(!error)setAnnouncement({title:"",content:""});}
  async function resolve(id:string,status:"resolved"|"dismissed"){if(!supabase)return;await supabase.from("reports").update({status}).eq("id",id);check();}
  if(loading)return <main><div className="page-wrap">관리자 권한 확인 중...</div></main>;
  if(!allowed)return <main><div className="page-wrap"><div className="empty">관리자 전용 페이지입니다.<br/><Link className="ghost" href="/">커뮤니티로 돌아가기</Link></div></div></main>;
  return <main><header className="topbar"><div className="nav-inner"><Link className="brand" href="/"><span className="brand-mark">J</span> JAPS 관리자</Link><nav><Link href="/">커뮤니티</Link><Link href="/japs">공식 홈페이지</Link></nav></div></header><div className="page-wrap"><div className="section-head"><div><span className="eyebrow">ADMIN</span><h1>운영 대시보드</h1></div></div><div className="content-grid"><section className="feed"><div className="panel"><span className="eyebrow">ANNOUNCEMENT</span><h2>공지 작성</h2><input value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})} placeholder="공지 제목" maxLength={160}/><textarea value={announcement.content} onChange={e=>setAnnouncement({...announcement,content:e.target.value})} placeholder="공지 내용을 입력하세요." rows={6} maxLength={5000}/><button className="primary" onClick={publish}>공지 게시</button>{message&&<p className="notice">{message}</p>}</div><div className="panel"><span className="eyebrow">REPORTS</span><h2>신고 관리 ({reports.length})</h2>{reports.length===0?<p>처리할 신고가 없습니다.</p>:reports.map(r=><div className="board-row" key={r.id}><div><strong>{r.reason}</strong><p>{r.status} · {new Date(r.created_at).toLocaleString("ko-KR")}</p><small>{r.post_id?`게시글 ${r.post_id}`:`댓글 ${r.comment_id}`}</small></div><div><button className="ghost" onClick={()=>resolve(r.id,"resolved")}>해결</button><button className="ghost" onClick={()=>resolve(r.id,"dismissed")}>기각</button></div></div>)}</div></section><aside className="side"><div className="panel"><strong>운영 원칙</strong><p>관리자 권한은 DB의 admin_users와 RLS로 검증됩니다. 브라우저에서 관리자 여부를 숨기는 방식이 아닙니다.</p></div><div className="panel muted"><strong>안전 점검</strong><p>신고, 공지, 게시글 삭제 등 운영 기능은 권한이 있는 계정만 실행할 수 있습니다.</p></div></aside></div></div></main>;
}
