"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { supabase, isSupabaseConfigured } from "../lib/supabase";

type User = { id: string; email?: string | null; isAnonymous?: boolean };
type SocialProvider = "google" | "discord";
type Post = { id: string; title: string; content: string; created_at: string; author_id?: string; category?: string; author?: { display_name?: string | null; username?: string | null; is_guest?: boolean } };
const demoPosts: Post[] = [
  { id: "demo-1", title: "잽스 커뮤니티에 오신 것을 환영합니다!", content: "여기에서 자유롭게 이야기하고 정보를 나눠보세요. 로그인하면 글을 작성할 수 있습니다.", created_at: new Date().toISOString(), category: "announcement", author: { display_name: "잽스 운영팀" } },
  { id: "demo-2", title: "오늘의 자유게시판", content: "궁금한 점이나 공유하고 싶은 이야기를 편하게 남겨주세요.", created_at: new Date(Date.now() - 3600000).toISOString(), category: "free", author: { display_name: "잽스" } },
];
const categoryLabel: Record<string, string> = { free: "자유", question: "질문", information: "정보", announcement: "공지" };
const DEVELOPER_EMAIL = "jkg2026826@gmail.com";

export default function Home() {
  const [user, setUser] = useState<User | null>(null); const [posts, setPosts] = useState<Post[]>(demoPosts); const [loading, setLoading] = useState(true); const [authOpen, setAuthOpen] = useState(false); const [authMode, setAuthMode] = useState<"login" | "signup">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [category, setCategory] = useState("free"); const [message, setMessage] = useState(""); const [posting, setPosting] = useState(false); const [recovering, setRecovering] = useState(false); const [guestLoading, setGuestLoading] = useState(false); const [socialLoading, setSocialLoading] = useState<SocialProvider | null>(null);
  const isDeveloper = user?.email?.toLowerCase() === DEVELOPER_EMAIL;
  const isGuest = Boolean(user?.isAnonymous);
  useEffect(() => { if (!supabase) { setLoading(false); return; } supabase.auth.getSession().then(({ data }) => { const u = data.session?.user; setUser(u ? { id: u.id, email: u.email, isAnonymous: u.is_anonymous } : null); }); const { data } = supabase.auth.onAuthStateChange((_event, session) => { const u = session?.user; setUser(u ? { id: u.id, email: u.email, isAnonymous: u.is_anonymous } : null); }); loadPosts(); return () => data.subscription.unsubscribe(); }, []);
  async function loadPosts() { if (!supabase) { setLoading(false); return; } const { data, error } = await supabase.from("posts").select("id,title,content,created_at,author_id,category").order("created_at", { ascending: false }).limit(30); if (!error && data) { const ids = [...new Set(data.map(p => p.author_id).filter(Boolean))]; const { data: profiles } = ids.length ? await supabase.from("profiles").select("id,display_name,username,is_guest").in("id", ids) : { data: [] }; setPosts(data.map(p => ({ ...p, author: profiles?.find(x => x.id === p.author_id) }))); } setLoading(false); }
  async function handleAuth(e: FormEvent) { e.preventDefault(); setMessage(""); if (!supabase) { setMessage("Supabase 환경변수가 아직 설정되지 않았어요."); return; } if (authMode === "signup" && password.length < 10) { setMessage("보안을 위해 비밀번호는 10자 이상이어야 합니다."); return; } const result = authMode === "login" ? await supabase.auth.signInWithPassword({ email: email.trim(), password }) : await supabase.auth.signUp({ email: email.trim(), password }); if (result.error) { setMessage("로그인 또는 회원가입 정보를 확인해주세요."); return; } setMessage(authMode === "signup" ? "가입 완료! 이메일 인증이 필요할 수 있어요." : "로그인되었습니다."); if (authMode === "login") setAuthOpen(false); }
  async function loginWithProvider(provider: SocialProvider) { if (!supabase) { setMessage("Supabase 환경변수가 아직 설정되지 않았어요."); return; } setSocialLoading(provider); setMessage(""); const { error } = await supabase.auth.signInWithOAuth({ provider, options: { redirectTo: `${window.location.origin}/` } }); if (error) { setSocialLoading(null); setMessage(provider === "google" ? "Google 로그인에 실패했습니다. 잠시 후 다시 시도해주세요." : "Discord 로그인에 실패했습니다. 잠시 후 다시 시도해주세요."); } }
  async function loginAsGuest() { if (!supabase) { setMessage("Supabase 환경변수가 아직 설정되지 않았어요."); return; } setGuestLoading(true); setMessage(""); const { error } = await supabase.auth.signInAnonymously(); setGuestLoading(false); if (error) { setMessage("게스트 계정을 만들 수 없습니다. Supabase에서 익명 로그인을 활성화해주세요."); return; } setAuthOpen(false); setMessage("게스트 계정으로 시작했습니다. 게시글에는 익명으로 표시됩니다."); }
  async function resetPassword() { if (!supabase || !email.trim()) { setMessage("비밀번호를 재설정할 이메일을 입력해주세요."); return; } setRecovering(true); setMessage(""); const { error } = await supabase.auth.resetPasswordForEmail(email.trim(), { redirectTo: `${window.location.origin}/profile` }); setRecovering(false); setMessage(error ? "비밀번호 재설정 요청에 실패했습니다." : "비밀번호 재설정 이메일을 확인해주세요."); }
  async function createPost(e: FormEvent) { e.preventDefault(); const cleanTitle = title.trim(); const cleanContent = content.trim(); if (!supabase || !user || !cleanTitle || !cleanContent) return; if (cleanTitle.length > 120 || cleanContent.length > 5000) { setMessage("제목은 120자, 내용은 5,000자 이내로 작성해주세요."); return; } setPosting(true); setMessage(""); const { error } = await supabase.from("posts").insert({ title: cleanTitle, content: cleanContent, category, author_id: user.id }); setPosting(false); if (error) { setMessage("게시글 등록에 실패했습니다. 잠시 후 다시 시도해주세요."); return; } setTitle(""); setContent(""); setCategory("free"); setMessage(isGuest ? "익명 게시글을 등록했습니다." : "게시글을 등록했습니다."); await loadPosts(); }
  async function logout() { if (!supabase) return; if (isGuest && !window.confirm("게스트 계정은 로그아웃하면 같은 게스트 계정으로 다시 로그인할 수 없습니다. 로그아웃할까요?")) return; await supabase.auth.signOut(); }
  const time = (value: string) => new Intl.DateTimeFormat("ko-KR", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
  const authorName = (post: Post) => post.author?.is_guest ? "익명" : (post.author?.display_name || post.author?.username || "익명");
  return <main><header className="topbar"><div className="nav-inner"><Link className="brand" href="/"><span className="brand-mark">J</span> 잽스 커뮤니티</Link><nav><Link href="#home">홈</Link><Link href="/posts">게시판</Link><Link href="#about">커뮤니티</Link></nav>{user ? <div className="account">{isDeveloper && <span className="developer-badge">🛠 잽스 커뮤니티 개발자</span>}{isGuest && <span className="guest-badge">👤 게스트 · 익명</span>}<Link href="/notifications">알림</Link>{!isGuest && <Link href="/profile">프로필</Link>}<span>{isGuest ? "익명 사용자" : user.email}</span><button className="ghost" onClick={logout}>로그아웃</button></div> : <div className="account-actions"><button className="secondary small" onClick={() => { setAuthMode("login"); setAuthOpen(true); }}>로그인</button><button className="primary small" onClick={() => { setAuthMode("signup"); setAuthOpen(true); }}>회원가입</button><button className="ghost small" onClick={loginAsGuest} disabled={guestLoading}>{guestLoading ? "시작 중..." : "게스트로 시작"}</button></div>}</div></header>
    <section id="home" className="hero wrap"><div><span className="eyebrow">JAPS COMMUNITY</span><h1>편하게 이야기하고<br/><em>함께 만들어가는</em> 커뮤니티.</h1><p>질문하고, 공유하고, 새로운 사람들과 연결되는 잽스 커뮤니티입니다.</p><div className="hero-actions"><Link className="primary" href="/posts">게시판 둘러보기 →</Link>{!user && <><button className="secondary" onClick={() => { setAuthMode("signup"); setAuthOpen(true); }}>회원가입</button><button className="ghost" onClick={loginAsGuest} disabled={guestLoading}>{guestLoading ? "시작 중..." : "익명으로 참여하기"}</button></>}</div></div><div className="hero-card"><div className="spark">✦</div><strong>{isGuest ? "익명으로 참여 중" : "오늘도 환영합니다"}</strong><p>{isGuest ? "개인정보 없이 자유롭게<br/>이야기를 나눠보세요." : "작은 이야기 하나가<br/>좋은 커뮤니티를 만듭니다."}</p></div></section>
    <section id="posts" className="wrap content-grid"><div className="feed"><div className="section-head"><div><span className="eyebrow">COMMUNITY</span><h2>최신 게시글</h2></div><Link className="ghost" href="/posts">전체 보기 →</Link></div>{loading ? <div className="empty">불러오는 중...</div> : posts.map(post => <article className="post" key={post.id}><div className="avatar">{authorName(post).slice(0,1)}</div><div className="post-body"><div className="post-meta"><strong>{authorName(post)}</strong><span>{time(post.created_at)}</span></div><Link href={`/posts/${post.id}`}><h3>{post.category && <span className="category-badge">{categoryLabel[post.category] || post.category}</span>} {post.title}</h3></Link><p>{post.content}</p><div className="post-foot"><span>♡ 좋아요</span><span>💬 댓글</span><span>게시글 보기 →</span></div></div></article>)}{posts.length === 0 && <div className="empty">아직 게시글이 없습니다.</div>}</div><aside className="side"><div className="panel"><span className="eyebrow">QUICK START</span><h3>커뮤니티 시작하기</h3><p>{isGuest ? "지금 익명으로 참여하고 있어요. 게시글은 다른 사람에게 익명으로 표시됩니다." : "로그인하면 나만의 게시글을 바로 작성할 수 있어요."}</p>{user ? <span className="status">● {isGuest ? "익명 참여 중" : "로그인됨"}</span> : <button className="primary full" onClick={() => setAuthOpen(true)}>로그인 / 회원가입</button>}</div><div id="about" className="panel muted"><strong>잽스 커뮤니티</strong><p>서로 존중하는 문화를 만들어요. 게스트는 이메일 없이 참여할 수 있으며 게시글과 댓글에는 익명으로 표시됩니다.</p></div></aside></section>
    {user && <section className="wrap composer"><span className="eyebrow">WRITE</span><h2>{isGuest ? "익명 글 작성" : "새 글 작성"}</h2><p className="composer-hint">{isGuest ? "현재 게스트 계정입니다. 작성자 이름은 다른 이용자에게 공개되지 않습니다." : "나의 계정으로 게시글을 작성합니다."}</p><form onSubmit={createPost}><select value={category} onChange={e => setCategory(e.target.value)}><option value="free">자유</option><option value="question">질문</option><option value="information">정보</option><option value="announcement">공지</option></select><input value={title} onChange={e => setTitle(e.target.value)} placeholder="제목" maxLength={120}/><textarea value={content} onChange={e => setContent(e.target.value)} placeholder="어떤 이야기를 나누고 싶나요?" rows={5} maxLength={5000}/><div className="compose-foot"><span>{message}</span><button className="primary" disabled={posting || !title.trim() || !content.trim()}>{posting ? "등록 중..." : "게시글 등록"}</button></div></form></section>}
    {authOpen && <div className="modal-backdrop" onMouseDown={() => setAuthOpen(false)}><div className="modal" onMouseDown={e => e.stopPropagation()}><button className="close" onClick={() => setAuthOpen(false)}>×</button><span className="eyebrow">JAPS</span><h2>{authMode === "login" ? "다시 만나서 반가워요" : "잽스에 가입하기"}</h2><p>{authMode === "login" ? "계정으로 로그인하세요." : "이메일과 비밀번호로 간단하게 시작하세요."}</p><div className="social-login"><button type="button" className="social-button google" onClick={() => loginWithProvider("google")} disabled={socialLoading !== null}>{socialLoading === "google" ? "Google 연결 중..." : "🔵 Google로 계속하기"}</button><button type="button" className="social-button discord" onClick={() => loginWithProvider("discord")} disabled={socialLoading !== null}>{socialLoading === "discord" ? "Discord 연결 중..." : "🎮 Discord로 계속하기"}</button></div><div className="auth-divider"><span>또는 이메일로</span></div><form onSubmit={handleAuth}><input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="이메일" autoComplete="email"/><input type="password" required minLength={authMode === "signup" ? 10 : 1} value={password} onChange={e => setPassword(e.target.value)} placeholder={authMode === "signup" ? "비밀번호 (10자 이상)" : "비밀번호"} autoComplete={authMode === "login" ? "current-password" : "new-password"}/><button className="primary full">{authMode === "login" ? "로그인" : "회원가입"}</button></form>{message && <div className="notice">{message}</div>}{authMode === "login" && <button className="switch" type="button" onClick={resetPassword} disabled={recovering}>{recovering ? "메일 전송 중..." : "비밀번호를 잊으셨나요? 이메일로 재설정"}</button>}<button className="guest-login" type="button" onClick={loginAsGuest} disabled={guestLoading}>{guestLoading ? "게스트 계정 생성 중..." : "✦ 이메일 없이 게스트로 참여"}</button><button className="switch" type="button" onClick={() => { setAuthMode(authMode === "login" ? "signup" : "login"); setMessage(""); }}>{authMode === "login" ? "처음이신가요? 회원가입" : "이미 계정이 있나요? 로그인"}</button>{!isSupabaseConfigured && <small>배포 전 NEXT_PUBLIC_SUPABASE_URL과 NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY를 설정하세요.</small>}</div></div>}<footer>© 2026 잽스 커뮤니티 · Built with Next.js & Supabase</footer></main>;
}
