"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { supabase } from "../../lib/supabase";

const DEVELOPER_EMAIL = "jkg2026826@gmail.com";

export default function ProfilePage() {
  const [user, setUser] = useState<any>(null); const [profile, setProfile] = useState<any>({});
  const [displayName, setDisplayName] = useState(""); const [username, setUsername] = useState(""); const [bio, setBio] = useState(""); const [avatarUrl, setAvatarUrl] = useState(""); const [message, setMessage] = useState("");
  const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [passwordMessage, setPasswordMessage] = useState(""); const [passwordBusy, setPasswordBusy] = useState(false);
  useEffect(() => { load(); }, []);
  async function load() { if (!supabase) return; const { data } = await supabase.auth.getSession(); if (!data.session) return; setUser(data.session.user); const { data: p } = await supabase.from("profiles").select("display_name,username,bio,avatar_url").eq("id", data.session.user.id).single(); if (p) { setProfile(p); setDisplayName(p.display_name ?? ""); setUsername(p.username ?? ""); setBio(p.bio ?? ""); setAvatarUrl(p.avatar_url ?? ""); } }
  async function save(e: FormEvent) { e.preventDefault(); if (!supabase || !user) return; setMessage(""); const cleanUsername = username.trim() || null; const cleanAvatar = avatarUrl.trim() || null; const { error } = await supabase.from("profiles").upsert({ id: user.id, display_name: displayName.trim(), username: cleanUsername, bio: bio.trim(), avatar_url: cleanAvatar }); setMessage(error ? (error.code === "23505" ? "이미 사용 중인 사용자 이름입니다." : error.message) : "프로필을 저장했습니다."); if (!error) setProfile({ display_name: displayName.trim(), username: cleanUsername, bio: bio.trim(), avatar_url: cleanAvatar }); }
  async function changePassword(e: FormEvent) { e.preventDefault(); if (!supabase || !user) return; setPasswordMessage(""); if (newPassword.length < 10) { setPasswordMessage("새 비밀번호는 10자 이상으로 설정해주세요."); return; } if (newPassword !== confirmPassword) { setPasswordMessage("새 비밀번호가 서로 일치하지 않습니다."); return; } setPasswordBusy(true); const { error } = await supabase.auth.updateUser({ password: newPassword }); setPasswordBusy(false); if (error) { setPasswordMessage(error.message); return; } setNewPassword(""); setConfirmPassword(""); setPasswordMessage("비밀번호를 안전하게 변경했습니다."); }
  async function signOut() { await supabase?.auth.signOut(); window.location.href = "/"; }
  if (!user) return <main><header className="topbar"><div className="nav-inner"><Link className="brand" href="/"><span className="brand-mark">J</span> 잽스 커뮤니티</Link></div></header><div className="page-wrap"><div className="empty">로그인 후 프로필을 볼 수 있습니다.</div></div></main>;
  const isDeveloper = user.email?.toLowerCase() === DEVELOPER_EMAIL;
  return <main><header className="topbar"><div className="nav-inner"><Link className="brand" href="/"><span className="brand-mark">J</span> 잽스 커뮤니티</Link><nav><Link href="/">홈</Link><Link href="/posts">게시판</Link><Link href="/notifications">알림</Link><button className="ghost" type="button" onClick={signOut}>로그아웃</button></nav></div></header><div className="page-wrap"><div className="profile-card"><div className="profile-avatar">{avatarUrl ? <img src={avatarUrl} alt="프로필" style={{width:"100%",height:"100%",objectFit:"cover",borderRadius:"50%"}}/> : (displayName || user.email || "J").slice(0,1).toUpperCase()}</div><div><span className="eyebrow">MY PROFILE</span><h1>{displayName || "내 프로필"}</h1>{isDeveloper && <div className="developer-badge profile-developer-badge">🛠 잽스 커뮤니티 개발자</div>}<p>{user.email}</p></div></div><form className="profile-form" onSubmit={save}><label>표시 이름<input value={displayName} onChange={e => setDisplayName(e.target.value)} maxLength={40} placeholder="닉네임"/></label><label>사용자 이름<input value={username} onChange={e => setUsername(e.target.value.replace(/[^a-zA-Z0-9_]/g, ""))} maxLength={24} placeholder="japs_user"/></label><label>프로필 사진 URL<input type="url" value={avatarUrl} onChange={e => setAvatarUrl(e.target.value)} placeholder="https://..."/></label><label>소개<textarea value={bio} onChange={e => setBio(e.target.value)} rows={5} maxLength={300} placeholder="나를 소개해보세요."/></label><div className="compose-foot"><span>{message}</span><button className="primary">저장</button></div></form><section className="security-card"><span className="eyebrow">ACCOUNT SECURITY</span><h2>계정 보안</h2><p>비밀번호는 다른 사이트와 다르게 설정하고, 다른 사람과 공유하지 마세요.</p><form className="profile-form" onSubmit={changePassword}><label>새 비밀번호<input type="password" value={newPassword} onChange={e => setNewPassword(e.target.value)} minLength={10} maxLength={128} autoComplete="new-password" placeholder="10자 이상" required/></label><label>새 비밀번호 확인<input type="password" value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} minLength={10} maxLength={128} autoComplete="new-password" placeholder="한 번 더 입력" required/></label><div className="compose-foot"><span>{passwordMessage}</span><button className="secondary" disabled={passwordBusy}>{passwordBusy ? "변경 중..." : "비밀번호 변경"}</button></div></form></section></div></main>;
}
